In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv('Telco_Customer_Churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
#converting the object into float

df.TotalCharges = pd.to_numeric(df.TotalCharges,errors = 'coerce')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [7]:
#wherever there is a null value it will drop because in totalcharges there is 11 values missing now. this will delete the whole row where value is empty.
df.dropna(how='any', inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [9]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [10]:
len(df)

7032

In [11]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [12]:
 y = df.Churn.values

In [13]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(7032,), dtype=object)

In [16]:
x =df.drop(['customerID','Churn'],axis=1)

In [17]:
x.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [18]:
#converting categorical features to numbericals ==> feature encoding   --(One Hot Encoding

x = pd.get_dummies(x, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first = True)

In [19]:
 x.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False

In [20]:
#splitting the data into test and train 

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [21]:
len(x_train)

5274

In [22]:
len(x_test)

1758

In [23]:
#feature scaling 
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
x_train_sc =  sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [24]:
x_train_sc

array([[-0.44415743, -1.25556331, -0.48775264, ..., -0.52189688,
        -0.7228536 ,  1.84155927],
       [-0.44415743,  1.14560082,  1.16834937, ..., -0.52189688,
         1.383406  , -0.54301809],
       [-0.44415743,  1.06420542, -1.3332801 , ...,  1.91608732,
        -0.7228536 , -0.54301809],
       ...,
       [-0.44415743,  0.98281003,  1.49956977, ..., -0.52189688,
        -0.7228536 ,  1.84155927],
       [-0.44415743, -0.27881858, -1.48141385, ..., -0.52189688,
        -0.7228536 ,  1.84155927],
       [-0.44415743, -0.52300476,  0.63573365, ..., -0.52189688,
         1.383406  , -0.54301809]], shape=(5274, 30))

In [25]:
x_test_sc

array([[-0.44415743,  1.59327549,  0.62075383, ..., -0.52189688,
         1.383406  , -0.54301809],
       [-0.44415743, -1.17416792,  0.91369248, ..., -0.52189688,
         1.383406  , -0.54301809],
       [ 2.25145395, -0.76719095,  0.32448633, ..., -0.52189688,
         1.383406  , -0.54301809],
       ...,
       [-0.44415743, -0.84858634, -0.66251718, ..., -0.52189688,
        -0.7228536 ,  1.84155927],
       [-0.44415743,  1.55257779,  0.45930469, ..., -0.52189688,
        -0.7228536 , -0.54301809],
       [-0.44415743, -0.48230707, -1.47142731, ..., -0.52189688,
        -0.7228536 ,  1.84155927]], shape=(1758, 30))

KNN Clasifier

In [26]:
#call the knn classifier 
from sklearn.neighbors import KNeighborsClassifier

#initiating the classifier
model = KNeighborsClassifier()

#passing the data to classifier
model.fit(x_train_sc, y_train)

KNeighborsClassifier()

In [27]:
y_pred = model.predict(x_test_sc)

In [28]:
y_pred

array(['No', 'Yes', 'No', ..., 'Yes', 'No', 'No'],
      shape=(1758,), dtype=object)

In [29]:
y_test

array(['No', 'No', 'Yes', ..., 'No', 'No', 'No'],
      shape=(1758,), dtype=object)

In [30]:
#classification metrics to check how the modelis behaving 

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.7707622298065984

In [31]:
print(accuracy_score(y_test, y_pred)*100)

77.07622298065984

Decision Tre Classifier

In [32]:
#call the decision tree classifier 
from sklearn.tree import DecisionTreeClassifier

#initiating the classifier
# model_dt = DecisionTreeClassifier()
model_dt = DecisionTreeClassifier(max_depth=2)

#passing the data to classifier
model_dt.fit(x_train_sc, y_train)

DecisionTreeClassifier(max_depth=2)

In [33]:
y_pred_dt = model_dt.predict(x_test_sc)

In [34]:
#classification metrics to check how the modelis behaving 

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred_dt)*100)

80.3754266211604

Random Forest Classifier

In [36]:
#call the random forest classifier 
from sklearn.ensemble import RandomForestClassifier

#initiating the classifier
model_rf = RandomForestClassifier(n_estimators=200)

#passing the data to classifier
model_rf.fit(x_train_sc, y_train)

RandomForestClassifier(n_estimators=200)

In [37]:
y_pred_rf = model_rf.predict(x_test_sc)

In [38]:
#classification metrics to check how the modelis behaving 

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred_rf)*100)

80.2047781569966

In [41]:
from sklearn.metrics import recall_score, precision_score

# Specify which label should be considered as the positive class
knn_recall = recall_score(y_test, y_pred, pos_label='Yes')

# If you also need precision score, apply the same fix
knn_precision = precision_score(y_test, y_pred, pos_label='Yes')


# Specify which label should be considered as the positive class
dt_recall = recall_score(y_test, y_pred_dt, pos_label='Yes')

# If you also need precision score, apply the same fix
dt_precision = precision_score(y_test, y_pred_dt, pos_label='Yes')

# Specify which label should be considered as the positive class
rf_recall = recall_score(y_test, y_pred_rf, pos_label='Yes')

# If you also need precision score, apply the same fix
rf_precision = precision_score(y_test, y_pred_rf, pos_label='Yes')

or we can do this also

In [46]:
from sklearn.metrics import classification_report

knn_report = classification_report(y_test, y_pred)

dt_report = classification_report(y_test, y_pred_dt)

rf_report = classification_report(y_test, y_pred_rf)

In [47]:
print('KNN Report ', knn_report)

KNN Report                precision    recall  f1-score   support

          No       0.84      0.86      0.85      1312
         Yes       0.55      0.52      0.54       446

    accuracy                           0.77      1758
   macro avg       0.70      0.69      0.69      1758
weighted avg       0.77      0.77      0.77      1758

In [48]:
print('DT Report ', dt_report)

DT Report                precision    recall  f1-score   support

          No       0.82      0.94      0.88      1312
         Yes       0.69      0.41      0.52       446

    accuracy                           0.80      1758
   macro avg       0.76      0.68      0.70      1758
weighted avg       0.79      0.80      0.79      1758

In [49]:
print('RF Report ', rf_report)

RF Report                precision    recall  f1-score   support

          No       0.84      0.91      0.87      1312
         Yes       0.65      0.48      0.55       446

    accuracy                           0.80      1758
   macro avg       0.74      0.69      0.71      1758
weighted avg       0.79      0.80      0.79      1758

In [51]:
from sklearn.metrics import classification_report

# These lines are already correct in your code
knn_roc_auc_report = classification_report(y_test, y_pred)

dt_roc_auc_report = classification_report(y_test, y_pred_dt)

rf_roc_auc_report = classification_report(y_test, y_pred_rf)

In [52]:
print('RF roc auc Report ', rf_roc_auc_report)

RF roc auc Report                precision    recall  f1-score   support

          No       0.84      0.91      0.87      1312
         Yes       0.65      0.48      0.55       446

    accuracy                           0.80      1758
   macro avg       0.74      0.69      0.71      1758
weighted avg       0.79      0.80      0.79      1758

Naive Baise Classifier

In [56]:
#call the Naive Baise classifier 
from sklearn.naive_bayes import BernoulliNB

#initiating the classifier
model_nb = BernoulliNB()

#passing the data to classifier
model_nb.fit(x_train_sc, y_train)

BernoulliNB()

In [57]:
y_pred_nb = model_nb.predict(x_test_sc)

In [58]:
#classification metrics to check how the modelis behaving 

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred_nb)*100)

72.58248009101251

Svm classifier

In [59]:
#call the svm classifier 
from sklearn.svm import SVC

#initiating the classifier
model_svc = SVC()

#passing the data to classifier
model_svc.fit(x_train_sc, y_train)

SVC()

In [60]:
y_pred_svc = model_svc.predict(x_test_sc)

In [61]:
#classification metrics to check how the modelis behaving 

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred_svc)*100)

80.88737201365188

Logistic Regression Classifier

In [62]:
#call the logistic regression classifier 
from sklearn.linear_model import LogisticRegression

#initiating the classifier
model_lr = LogisticRegression()

#passing the data to classifier
model_lr.fit(x_train_sc, y_train)

LogisticRegression()

In [63]:
y_pred_lr = model_lr.predict(x_test_sc)

In [64]:
#classification metrics to check how the modelis behaving 

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred_lr)*100)

81.51308304891923