In [1]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\dell\anaconda3\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('Churn_Modelling.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9926 non-null   object
 6   Age              9909 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [5]:
df.isnull().sum()

RowNumber           0
CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender             74
Age                91
Tenure              0
Balance             0
NumOfProducts       0
HasCrCard           0
IsActiveMember      0
EstimatedSalary     0
Exited              0
dtype: int64

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,NaN,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,NaN,NaN,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [10]:
df1=df.describe().round(2)  #it will display statical values only remove catogarical values.
df1

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00,10000.00,10000.00,9909.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.0
mean,5000.50,15690940.57,650.53,38.92,5.01,76485.89,1.53,0.71,0.52,100090.24,0.2
std,2886.90,71936.19,96.65,10.50,2.89,62397.41,0.58,0.46,0.50,57510.49,0.4
min,1.00,15565701.00,350.00,18.00,0.00,0.00,1.00,0.00,0.00,11.58,0.0
25%,2500.75,15628528.25,584.00,32.00,3.00,0.00,1.00,0.00,0.00,51002.11,0.0
50%,5000.50,15690738.00,652.00,37.00,5.00,97198.54,1.00,1.00,1.00,100193.92,0.0
75%,7500.25,15753233.75,718.00,44.00,7.00,127644.24,2.00,1.00,1.00,149388.25,0.0
max,10000.00,15815690.00,850.00,92.00,10.00,250898.09,4.00,1.00,1.00,199992.48,1.0

Normalization

In [9]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,NaN,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,NaN,NaN,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [25]:
new_df2=pd.DataFrame(df,columns=['Age','Tenure','Ve'])

In [26]:
new_df2.head(5)

    Age  Tenure  Ve
0   NaN       2 NaN
1  41.0       1 NaN
2   NaN       8 NaN
3  39.0       1 NaN
4  43.0       2 NaN

In [28]:
new_df=pd.DataFrame(df,columns=['Age','Tenure'])
new_df

       Age  Tenure
0      NaN       2
1     41.0       1
2      NaN       8
3     39.0       1
4     43.0       2
...    ...     ...
9995  39.0       5
9996  35.0      10
9997  36.0       7
9998  42.0       3
9999  28.0       4

[10000 rows x 2 columns]

In [34]:
new_df['Age']=new_df['Age'].fillna(new_df['Age'].mean())  #it will fill null value with mean which is calculated through whole column value.

In [35]:
new_df['Age']

0       38.92088
1       41.00000
2       38.92088
3       39.00000
4       43.00000
          ...
9995    39.00000
9996    35.00000
9997    36.00000
9998    42.00000
9999    28.00000
Name: Age, Length: 10000, dtype: float64

In [36]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     10000 non-null  float64
 1   Tenure  10000 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 156.4 KB

In [37]:
new_df.head()

        Age  Tenure
0  38.92088       2
1  41.00000       1
2  38.92088       8
3  39.00000       1
4  43.00000       2

In [38]:
new_df['Tenure'].isnull().sum()

0

In [39]:
new_df['Age'].isnull().sum()

0

In [40]:
scaler=MinMaxScaler()
normalized_df=scaler.fit_transform(new_df)
print(normalized_df)                        #x1=(x-xmin)/(xmax-mmin) x1 is to indicate normalized_df

[[0.28271459 0.2       ]
 [0.31081081 0.1       ]
 [0.28271459 0.8       ]
 ...
 [0.24324324 0.7       ]
 [0.32432432 0.3       ]
 [0.13513514 0.4       ]]

Standardization

In [41]:
scaler=StandardScaler()
standardized_df=scaler.fit_transform(new_df)
print(standardized_df)

[[ 0.         -1.04175968]
 [ 0.19889066 -1.38753759]
 [ 0.          1.03290776]
 ...
 [-0.27941425  0.68712986]
 [ 0.29455164 -0.69598177]
 [-1.04470209 -0.35020386]]