In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Churn_Modelling.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9926 non-null   object
 6   Age              9909 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [3]:
df.isnull().sum()

RowNumber           0
CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender             74
Age                91
Tenure              0
Balance             0
NumOfProducts       0
HasCrCard           0
IsActiveMember      0
EstimatedSalary     0
Exited              0
dtype: int64

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,NaN,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,NaN,NaN,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [6]:
df.drop(columns=["CustomerId", "RowNumber", "Surname"], axis=1, inplace=True)

In [7]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,NaN,NaN,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,502,France,NaN,NaN,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [8]:
df.Gender.value_counts()

Gender
Male      5422
Female    4504
Name: count, dtype: int64

In [9]:
df.Gender.mode()

0    Male
Name: Gender, dtype: object

In [10]:
df['Gender'] = df['Gender'].fillna('Male')

In [11]:
df.Gender.value_counts()

Gender
Male      5496
Female    4504
Name: count, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              9909 non-null   float64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(3), int64(6), object(2)
memory usage: 859.5+ KB

Label Encoding

In [16]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
df['Gender_label'] = le.fit_transform(df.Gender.values)

In [17]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label
0,619,France,Male,NaN,2,0.00,1,1,1,101348.88,1,1
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,0
2,502,France,Male,NaN,8,159660.80,3,1,0,113931.57,1,1
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,0

In [18]:
df.Gender_label.value_counts()

Gender_label
1    5496
0    4504
Name: count, dtype: int64

In [19]:
one_hot = pd.get_dummies(df['Geography'])

In [20]:
one_hot

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [21]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label
0,619,France,Male,NaN,2,0.00,1,1,1,101348.88,1,1
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,0
2,502,France,Male,NaN,8,159660.80,3,1,0,113931.57,1,1
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,0

In [22]:
df_dummies = pd.get_dummies(df)
df_dummies.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,NaN,2,0.00,1,1,1,101348.88,1,1,True,False,False,False,True
1,608,41.0,1,83807.86,1,0,1,112542.58,0,0,False,False,True,True,False
2,502,NaN,8,159660.80,3,1,0,113931.57,1,1,True,False,False,False,True
3,699,39.0,1,0.00,2,0,0,93826.63,0,0,True,False,False,True,False
4,850,43.0,2,125510.82,1,1,1,79084.10,0,0,False,False,True,True,False

In [23]:
df_dummies_de = pd.get_dummies(df, drop_first=True)

df_dummies_de.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_Germany,Geography_Spain,Gender_Male
0,619,NaN,2,0.00,1,1,1,101348.88,1,1,False,False,True
1,608,41.0,1,83807.86,1,0,1,112542.58,0,0,False,True,False
2,502,NaN,8,159660.80,3,1,0,113931.57,1,1,False,False,True
3,699,39.0,1,0.00,2,0,0,93826.63,0,0,False,False,False
4,850,43.0,2,125510.82,1,1,1,79084.10,0,0,False,True,False